#!/bin/bash

pwd
cd poky

pwd
source oe-init-build-env build-atmel

pwd
cp ../../../meta-embedded-bagels/buildconf/*.conf conf/

echo ""
echo "Embedded Bagels targets are:"
echo "    core-image-minimal"
echo "    atmel-qt5-demo-image"
echo ""
echo "Supported MACHINEs"
echo "    MACHINE ??= \"at91sam9rlek\""
echo "    MACHINE ??= \"at91sam9m10g45ek\""
echo "    MACHINE ??= \"at91sam9x5ek\""
echo "    MACHINE ??= \"sama5d3xek\""
echo "    MACHINE ??= \"sama5d3-xplained\""
echo "    MACHINE ??= \"sama5d4ek\""
echo "    MACHINE ??= \"sama5d4-xplained\""
echo ""
echo "Usage:"
echo "    MACHINE=sama5d4-xplained bitbake core-image-minimal"
echo "    MACHINE=sama5d4-xplained bitbake atmel-qt5-demo-image"
echo ""
